name: nebula
recipe: drupal9
config:
  php: '7.4'
  via: apache
  database: mariadb:10.4
  webroot: web
  drush: ^10
proxy:
  appserver:
    - oa.lndo.site
    - www.ombudsmanassociation.org
  phpmyadmin:
    - oa.mysql.lndo.site
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
    xdebug: true
    build_as_root:
      - apt-get update -y
      - apt-get install git-flow -y
      - apt-get install nano -y
      - apt-get install vim -y
      - apt-get install net-tools -y
      - apt-get install memcached -y
      - apt-get install libmemcached-dev -y
      - apt-get install cron -y
      - apt-get install curl -y
      - apt-get install zip unzip -y
      - apt-get install imagemagick -y
    run_as_root:
      - echo "*/1 * * * * drush --root=/var/www/html/web --quiet core-cron --yes" | crontab -
      - service cron start
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
    hosts:
