name: nebula
recipe: drupal8
config:
  php: '7.2'
  via: apache:2.4
  database: mariadb:10.2
  webroot: web
  drush: ^8
  xdebug: true
services:
  appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install git-flow -y
      - apt-get install nano -y
      - apt-get install vim -y
      - apt-get install net-tools -y
      - apt-get install memcached -y
      - apt-get install libmemcached-dev -y:q
      - apt-get install clamav clamav-daemon -y
      - apt-get install cron -y
      - apt-get install curl -y
      - apt-get install zip unzip -y
      - apt-get install imagemagick -y
      - docker-php-ext-enable memcached
    run_as_root:
      - crontab /app/scripts/cron
      - service cron start
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
